sprint 10
RespectRus/ImageFeed pull request #4
Opened 2023-01-23 09:35 UTC by RespectRus

2023-02-04 11:10 UTC, IBDesignable requested changes

2023-02-04 11:10 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +    private let ShowWebViewSegueIdificator = "ShowWebView"
Рекомендую использовать общепринятые правила по неймингу свойств и констант, это не тип, поэтому лучше использовать camelCase

И вместо Idificator использовать английское слово identifier 
Чтобы замечать подобные опечатки можно включить проверку правописания https://sarunw.com/posts/spell-checking-in-xcode/

2023-02-04 11:10 UTC, IBDesignable commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
нужно проверить по документации правильность, не могу авторизоваться с такими правами

2023-02-04 11:10 UTC, IBDesignable commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
Это тоже константы, а не типы, поэтому рекомендую перейти на camelCase 

К тому же глобальный контекст в swift не принят, и обычно такие вещи упаковывают в пространство имен через enum 

```
enum Constants {
static let key = "AAA"
}
```

2023-02-04 11:10 UTC, IBDesignable commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +            httpMetod: "POST",
URLComponents для такой задачи подходят больше, рекомендую переписать

2023-02-04 11:10 UTC, IBDesignable commented on ImageFeed/Service/OAuth2/OAuth2TokenStorage.swift
> +    var token: String? {
давай поправим отсупы (control +i) и разделим свойства одной пустой строкой, чтобы не слипалось

2023-02-06 06:15 UTC, RespectRus commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
let defaultBaseURL = URL(string: "https://api.unsplash.com")!
 
В адресной строке была ошибка, в конце стоял лишний "/"

2023-02-06 06:41 UTC, RespectRus commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
В проекте курса (авторское решение), константы указаны с заглавной буквы, поэтому и исправил)) В пред буду внимательней, спасибо!)
`import Foundation

let AccessKey = "<ваш Access Key>"
let SecretKey = "<ваш Secret Key>"
let RedirectURI = "<ваш Redirect URI>"
let AccessScope = "public+read_user+write_likes"
let DefaultBaseURL = URL(string: "https://api.unsplash.com")!
`

2023-02-06 06:42 UTC, RespectRus commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
В проекте курса (авторское решение), константы указаны с заглавной буквы, поэтому и исправил)) В пред буду внимательней, спасибо!)
```
import Foundation

let AccessKey = "<ваш Access Key>"
let SecretKey = "<ваш Secret Key>"
let RedirectURI = "<ваш Redirect URI>"
let AccessScope = "public+read_user+write_likes"
let DefaultBaseURL = URL(string: "https://api.unsplash.com/")!
```

2023-02-06 06:43 UTC, RespectRus commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
В проекте курса (авторское решение), константы указаны с заглавной буквы, поэтому и исправил)) Буду внимательней, спасибо!)
```
import Foundation

let AccessKey = "<ваш Access Key>"
let SecretKey = "<ваш Secret Key>"
let RedirectURI = "<ваш Redirect URI>"
let AccessScope = "public+read_user+write_likes"
let DefaultBaseURL = URL(string: "https://api.unsplash.com/")!
```

2023-02-06 18:58 UTC, IBDesignable commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
А я вот такой тип прав нашла: **write_likes**

2023-02-06 18:59 UTC, IBDesignable commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
Все-так, ты верно сделал. Я навязываю свой опыт :) но опираюсь честно-честно на общепринятые гайды:

- [Подробное описание codestyle](https://google.github.io/swift/) от Google
- [От Ray Wanderlich](https://github.com/raywenderlich/swift-style-guide)
- [На русском от команды tutu](https://github.com/tutu-ru/swift-style-guide)

2023-02-06 19:02 UTC, IBDesignable commented on ImageFeed/Helpers/Constants.swift
> +let AccessScope = "public+read_user+write_like"
<img width="505" alt="Снимок экрана 2023-02-06 в 21 02 15" src="https://user-images.githubusercontent.com/121577115/217061436-9c982a90-4870-4dfe-a95c-6b45d945f6ee.png">

2023-02-07 20:24 UTC, IBDesignable approved these changes

2023-02-08 09:11 UTC, merged